apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-volume
  namespace: postgresql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  hostPath:
    path: /var/local/postgresql

---    
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
  namespace: postgresql
spec:
  storageClassName: manual
  volumeName: postgresql-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi