apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitor-volume
  namespace: monitor
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  hostPath:
    path: /var/local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitor-pvc
  namespace: monitor
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi